/*
-- Query: 
-- Date: 2014-04-20 14:07
*/
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('A. Testoni');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Adidas');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Alden');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Allen Edmonds');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Asics');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Bass');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Bates');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Berluti');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Birkenstock');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Bostonian');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Brass Boot');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Bruno Magli');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Calvin Klein');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Caterpillar');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Clarks');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Cola Haan');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Columbia');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Converse');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Crevo');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Crockett & Jones');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Crocs');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Dan Post');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('DC Shoes');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Deer Stags');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Dingo');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Dockers');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Dolce & Gabbana');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Dr. Martens');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Dr. Martens Industrial');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Dr. Scholl\'s');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Dr. Scholl\'s Work');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Dr. Tuxedo by Benjamin Walk');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Florsheim Shoe');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Florsheim Work');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('GBX');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Giorgio Brutini');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Gucci');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Harley Davidson');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Hi-Tec');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Iron Age');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Island Surf');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('J.M. Weston');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Jimmy Choo');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('John Deere');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('John Lobb Bootmaker');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('John Varvatos');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Johnston & Murphy');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('K-Swiss');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Kamik');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Kenneth Cole Productions');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Khombu');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('L.B Evans');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Laredo');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Lugz');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Madden');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Magnum');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Margaritaville');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Mark Nason Skechers');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('McRae');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Neil M Footwear');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('New Balance');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Nike');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Nunn Bush');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Prada');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Propet');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Puma');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Reebok');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Reebok Duty');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Reebok Work');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Rockport');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Rockport Works');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Rugged Shark');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('RW by Robert Wayne');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Salvatore Ferragamo');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Santoni');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Saucony');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Skechers');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Sorel');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Sperry Top-Sider');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Stacy Adams');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Streetcars');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Teva');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Timberland');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Timberland Pro');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Tod\'s');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Vans');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Wenger Swiss Army');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Wolverine');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Woolrich');
INSERT INTO `ShoeBrands` (`Brand`) VALUES ('Yves Saint-Laurent');
