Sizetype.create!([
  {SizeType: "Europe",        ToMondo1: 6.66667,  ToMondo0: -10.0,    SizeTypeInterval: 0.5,  MinSize: 32.0,  MaxSize: 49.0},
  {SizeType: "Mondopoint",    ToMondo1: 1.0,      ToMondo0: 0.0,      SizeTypeInterval: 5.0,  MinSize: 200.0, MaxSize: 320.0},
  {SizeType: "UK/Australia",  ToMondo1: 8.46667,  ToMondo0: 201.667,  SizeTypeInterval: 0.5,  MinSize: 0.0,   MaxSize: 14.0},
  {SizeType: "US/Canada",     ToMondo1: 8.46667,  ToMondo0: 292.0,    SizeTypeInterval: 0.5,  MinSize: 1.0,   MaxSize: 15.0}
])
Gender.create!([
  {Gender: "F"},
  {Gender: "M"}
])
Lengthfit.create!([
  {LengthFit: "Perfect"},
  {LengthFit: "Slightly Long"},
  {LengthFit: "Slightly Short"},
  {LengthFit: "Too Long"},
  {LengthFit: "Too Short"}
])
Shoebrand.create!([
  {Brand: "A. Testoni"},
  {Brand: "Adidas"},
  {Brand: "Alden"},
  {Brand: "Allen Edmonds"},
  {Brand: "Asics"},
  {Brand: "Bass"},
  {Brand: "Bates"},
  {Brand: "Berluti"},
  {Brand: "Birkenstock"},
  {Brand: "Bostonian"},
  {Brand: "Brass Boot"},
  {Brand: "Bruno Magli"},
  {Brand: "Calvin Klein"},
  {Brand: "Caterpillar"},
  {Brand: "Clarks"},
  {Brand: "Cola Haan"},
  {Brand: "Columbia"},
  {Brand: "Converse"},
  {Brand: "Crevo"},
  {Brand: "Crockett & Jones"},
  {Brand: "Crocs"},
  {Brand: "Dan Post"},
  {Brand: "DC Shoes"},
  {Brand: "Deer Stags"},
  {Brand: "Dingo"},
  {Brand: "Dockers"},
  {Brand: "Dolce & Gabbana"},
  {Brand: "Dr. Martens"},
  {Brand: "Dr. Martens Industrial"},
  {Brand: "Dr. Scholl's"},
  {Brand: "Dr. Scholl's Work"},
  {Brand: "Dr. Tuxedo by Benjamin Walk"},
  {Brand: "Florsheim Shoe"},
  {Brand: "Florsheim Work"},
  {Brand: "GBX"},
  {Brand: "Giorgio Brutini"},
  {Brand: "Gucci"},
  {Brand: "Harley Davidson"},
  {Brand: "Hi-Tec"},
  {Brand: "Iron Age"},
  {Brand: "Island Surf"},
  {Brand: "J.M. Weston"},
  {Brand: "Jimmy Choo"},
  {Brand: "John Deere"},
  {Brand: "John Lobb Bootmaker"},
  {Brand: "John Varvatos"},
  {Brand: "Johnston & Murphy"},
  {Brand: "K-Swiss"},
  {Brand: "Kamik"},
  {Brand: "Kenneth Cole Productions"},
  {Brand: "Khombu"},
  {Brand: "L.B Evans"},
  {Brand: "Laredo"},
  {Brand: "Lugz"},
  {Brand: "Madden"},
  {Brand: "Magnum"},
  {Brand: "Margaritaville"},
  {Brand: "Mark Nason Skechers"},
  {Brand: "McRae"},
  {Brand: "Neil M Footwear"},
  {Brand: "New Balance"},
  {Brand: "Nike"},
  {Brand: "Nunn Bush"},
  {Brand: "Prada"},
  {Brand: "Propet"},
  {Brand: "Puma"},
  {Brand: "Reebok"},
  {Brand: "Reebok Duty"},
  {Brand: "Reebok Work"},
  {Brand: "Rockport"},
  {Brand: "Rockport Works"},
  {Brand: "Rugged Shark"},
  {Brand: "RW by Robert Wayne"},
  {Brand: "Salvatore Ferragamo"},
  {Brand: "Santoni"},
  {Brand: "Saucony"},
  {Brand: "Skechers"},
  {Brand: "Sorel"},
  {Brand: "Sperry Top-Sider"},
  {Brand: "Stacy Adams"},
  {Brand: "Streetcars"},
  {Brand: "Teva"},
  {Brand: "Timberland"},
  {Brand: "Timberland Pro"},
  {Brand: "Tod's"},
  {Brand: "Vans"},
  {Brand: "Wenger Swiss Army"},
  {Brand: "Wolverine"},
  {Brand: "Woolrich"},
  {Brand: "Yves Saint-Laurent"}
])
Shoematerial.create!([
  {Material: "Leather"},
  {Material: "Leatherette"},
  {Material: "Polyurethane"},
  {Material: "PVC"},
  {Material: "Rubber"}
])
Shoestyle.create!([
  {Style: "Boot"},
  {Style: "Boat Shoe"},
  {Style: "Brouge"},
  {Style: "Cross Trainer"},
  {Style: "Derby"},
  {Style: "Dress Boot"},
  {Style: "Dress Shoe"},
  {Style: "Driving Shoe"},
  {Style: "Hiker"},
  {Style: "Loafer (Slip-on)"},
  {Style: "Oxford (Lace-up)"},
  {Style: "Patent Leather"},
  {Style: "Penny Loafer"},
  {Style: "Runner"},
  {Style: "Saddle Shoe"},
  {Style: "Sandal"},
  {Style: "Slipper"},
  {Style: "Sneaker"},
  {Style: "Tennis"},
  {Style: "Walker"},
  {Style: "Wingtip"},
  {Style: "Work Boot"}
])
